title = 'Pow of Formal Power Series'
timelimit = 10
forum = "https://github.com/yosupo06/library-checker-problems/issues/386"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "lower_deg_zero.cpp"
    number = 8
[[tests]]
    name = "all_zero.cpp"
    number = 2
[[tests]]
    name = "monomial.cpp"
    number = 4
[[tests]]
    name = "lower_deg_zero2.cpp"
    number = 4


[params]
    N_MAX = 500000
    M_MAX = 1000000000
    MOD = 998244353
