title = 'Enumerate Triangles'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/442"

[[tests]]
	name = "example.in"
	number = 1
[[tests]]
	name = "minimum.in"
	number = 1
[[tests]]
	name = "small_sparse.cpp"
	number = 3
[[tests]]
	name = "small_dense.cpp"
	number = 3
[[tests]]
	name = "large_random.cpp"
	number = 3
[[tests]]
	name = "max_random.cpp"
	number = 3
[[tests]]
	name = "star.cpp"
	number = 2

[[solutions]]
	name = 'naive.cpp'
	wrong = true
[[solutions]]
	name = 'correct_slow.cpp'
	wrong = false
[[solutions]]
	name = "deg_2.cpp"
	wrong = true

[params]
	N_MIN = 1
	N_MAX = 100_000
	M_MIN = 1
	M_MAX = 100_000
	MOD = 998_244_353
