title = 'Factorial'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/128"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 8
[[tests]]
    name = "near_max.cpp"
    number = 3
[[tests]]
    name = "near_half.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = false


[params]
    MOD = 998244353
