steps:
  - id: generate_and_deploy
    name: yosupo/library-checker-problems-deploy
    entrypoint: sh
    args:
      - '-c'
      - 'pip3 install -r requirements.txt && pip3 install grpcio grpcio-tools minio && ulimit -s unlimited && ./deploy.py --host=apiv1.yosupo.jp --prod'
    env:
      - 'API_PASS=$_API_PASS'
      - 'MINIO_HOST=$_MINIO_HOST'
      - 'MINIO_ACCESS_KEY=$_MINIO_ACCESS_KEY'
      - 'MINIO_SECRET_KEY=$_MINIO_SECRET_KEY'
      - 'MINIO_BUCKET=$_MINIO_BUCKET'

timeout: 3600s
