steps:
  # until the db migration step is finished
  # https://cloud.google.com/sql/docs/postgres/sql-proxy
  - id: proxy
    name: gcr.io/cloudsql-docker/gce-proxy
    entrypoint: sh
    args:
      - '-c'
      - '/cloud_sql_proxy -dir=/cloudsql -instances=$_PG_NAME & while [ ! -f /cloudsql/stop ]; do sleep 2; done'
    waitFor: ['-']
    volumes:
      - name: db
        path: /cloudsql

  - id: generate_and_deploy
    name: yosupo/library-checker-problems-deploy
    entrypoint: sh
    args:
      - '-c'
      - 'ulimit -s unlimited && ./generate.py problems.toml && ./deploy.py'
    env: ['POSTGRE_HOST=/cloudsql/$_PG_NAME', 'POSTGRE_PASS=$_PG_PASS']
    volumes:
      - name: db
        path: /cloudsql
    waitFor: ['-']
  - name: yosupo/library-checker-problems-deploy
    args: ['touch', '/cloudsql/stop']
    volumes:
      - name: db
        path: /cloudsql
    waitFor: ['generate_and_deploy']

timeout: 1800s
