[[Problems]]
    Title = 'A + B'
    Dir = 'sample/aplusb'

[[Problems]]
    Title = 'Unionfind'
    Dir = 'datastructure/unionfind'

[[Problems]]
    Title = 'Z-algorithm'
    Dir = 'string/zalgorithm'

[[Problems]]
    Title = 'Run-enumerate'
    Dir = 'string/runenumerate'

[[Problems]]
    Title = 'Determinant of Matrix(Mod 998244353)'
    Dir = 'math/matrix_det'

[[Problems]]
    Title = 'Convolution(Mod 998244353)'
    Dir = 'math/convolution_mod'
