[problems.simple_aplusb]
    title = 'Simple AplusB'
    dir = 'test/simple_aplusb'

[problems.failed_verify]
    title = 'Failed Verify'
    dir = 'test/failed_verify'

[problems.unuse_example]
    title = 'Unuse Example'
    dir = 'test/unuse_example'

[problems.unuse_gen]
    title = 'Unuse Gen'
    dir = 'test/unuse_gen'
