[[problems]]
    title = 'A + B'
    dir = 'sample/aplusb'

[[problems]]
    title = 'Unionfind'
    dir = 'datastructure/unionfind'

[[problems]]
    title = 'Static RMQ'
    dir = 'datastructure/staticrmq'

[[problems]]
    title = 'Z Algorithm'
    dir = 'string/zalgorithm'

[[problems]]
    title = 'Run Enumerate'
    dir = 'string/runenumerate'

[[problems]]
    title = 'Determinant of Matrix(Mod 998244353)'
    dir = 'math/matrix_det'

[[problems]]
    title = 'Determinant of Sparse Matrix(Mod 998244353)'
    dir = 'math/sparse_matrix_det'

[[problems]]
    title = 'Convolution(Mod 998244353)'
    dir = 'math/convolution_mod'
