[[Problems]]
    Title = 'A + B'
    Dir = 'sample/aplusb'

[[Problems]]
    Title = 'Unionfind'
    Dir = 'datastructure/unionfind'

[[Problems]]
    Title = 'Z-algorithm'
    Dir = 'string/zalgorithm'
