[problems.simple_aplusb]
    dir = 'test/simple_aplusb'

[problems.failed_verify]
    dir = 'test/failed_verify'

[problems.unused_example]
    dir = 'test/unused_example'

[problems.unused_gen]
    dir = 'test/unused_gen'

[problems.this_is_differ_id]
    dir = 'test/differ_id'
