[problems.aplusb]
    title = 'A + B'
    dir = 'sample/aplusb'

[problems.unionfind]
    title = 'Unionfind'
    dir = 'datastructure/unionfind'

[problems.staticrmq]
    title = 'Static RMQ'
    dir = 'datastructure/staticrmq'

[problems.lca]
    title = 'Lowest Common Ancestor'
    dir = 'graph/lca'

[problems.bipartitematching]
    title = 'Matching on Bipartite Graph'
    dir = 'graph/bipartitematching'

[problems.assignment]
    title = 'Assignment Problem'
    dir = 'graph/assignment'

[problems.zalgorithm]
    title = 'Z Algorithm'
    dir = 'string/zalgorithm'

[problems.suffixarray]
    title = 'Suffix Array'
    dir = 'string/suffixarray'

[problems.runenumerate]
    title = 'Run Enumerate'
    dir = 'string/runenumerate'

[problems.factorize]
    title = 'Factorize'
    dir = 'math/factorize'

[problems.matrix_det]
    title = 'Determinant of Matrix(Mod 998244353)'
    dir = 'math/matrix_det'

[problems.sparse_matrix_det]
    title = 'Determinant of Sparse Matrix(Mod 998244353)'
    dir = 'math/sparse_matrix_det'

[problems.convolution_mod]
    title = 'Convolution(Mod 998244353)'
    dir = 'math/convolution_mod'
