solution = "correct.cpp"
verify = "verify.cpp"
timelimit = 5.0

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5

[[solutions]]
    name = 'correct.cpp'
[[solutions]]
    name = 'reverse_order.cpp'    
    wrong = true