solution = "correct.cpp"
verify = 'verify.cpp'
timelimit = 2.0

[[tests]]
    Name = "example.in"
    Number = 4

[[tests]]
    Name = "random.cpp"
    Number = 5

[[tests]]
    Name = "max_random.cpp"
    Number = 5

[[tests]]
    Name = "all_same.cpp"
    Number = 5

[[tests]]
    Name = "fib_str.cpp"
    Number = 5
