timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/51"

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5

[[tests]]
    name = "all_same.cpp"
    number = 5

[[tests]]
    name = "fib_str.cpp"
    number = 5
