title = 'Inv of Formal Power Series'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/120"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "max_random_or_zero.cpp"
    number = 1
