title = 'Minimum cost b-flow'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/143"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "empty.in"
    number = 4
[[tests]]
    name = "near_minimum.cpp"
    number = 1
[[tests]]
    name = "near_maximum.cpp"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 10
[[tests]]
    name = "large_random.cpp"
    number = 10

[params]
    N_MAX = 100
    M_MAX = 1_000
    U_MAX = 1_000_000_000
    C_MAX = 1_000_000_000
    P_MAX = 1_000_000_000_000_000

