solution = "correct.cpp"
verify = "verify.cpp"
timelimit = 10.0

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "big2.cpp"
    number = 3
