title = 'Factorize'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/41"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "big2.cpp"
    number = 3

[params]
    MAX_Q = 100
    MAX_A = 1_000_000_000_000_000_000
