title = 'Matching on Bipartite Graph'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/37"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 10
