solution = "correct.cpp"
verify = "verify.cpp"
timelimit = 10.0

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "handmade.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 10
