version: 2

jobs:
  clang-compile:
    docker:
      - image: gcr.io/library-checker-project/library-checker-problem-env-new
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            ./generate.py problems.toml --compileonly
          environment:           
            CXX: clang++
            CXXFLAGS: -std=c++14 -stdlib=libc++ -Wall -Wextra
  generate:
    docker:
      - image: gcr.io/library-checker-project/library-checker-problem-env-new
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            ulimit -s unlimited
            ./generate.py problems.toml
            ./deploy.py --htmldir /tmp/html --htmlonly
      - store_artifacts:
          path: /tmp/html
          
workflows:
  version: 2
  build:
    jobs:
      - clang-compile
      - generate
