version: 2

jobs:
  clang:
    docker:
      - image: circleci/python:3.5.7-stretch
    steps:
      - checkout
      - run:
          command: |
            apt-get install -y g++ clang libc++-dev libc++abi-dev
            pip install --user -r requirements.txt
            ulimit -s unlimited
            ./generate.py problems.toml --verify --sol
          environment:           
            CXX: clang++
            CXXFLAGS: -O2 -std=c++14 -stdlib=libc++ -Wall -Wextra -Werror
  generate:
    docker:
      - image: circleci/python:3.5.7-stretch
    steps:
      - checkout
      - run:
          command: |
            pip install --user -r requirements.txt
            ulimit -s unlimited
            ./generate.py problems.toml --verify --sol --html --htmldir=/tmp/html
      - store_artifacts:
          path: /tmp/html
  genhtml:
    docker:
      - image: yosupo/library-checker-problems-deploy
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ./deploy.py --htmldir /tmp/html --htmlonly

workflows:
  version: 2
  build:
    jobs:
      - clang
      - generate
