version: 2

jobs:
  clang-compile:
    docker:
      - image: yosupo/library-checker-problems-generate
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            ./generate.py problems.toml --compileonly
          environment:           
            CXX: clang++
            CXXFLAGS: -std=c++14 -stdlib=libc++ -Wall -Wextra
  generate:
    docker:
      - image: yosupo/library-checker-problems-generate
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            ulimit -s unlimited
            ./generate.py problems.toml
      - persist_to_workspace:
          root: .
          paths:
            # sample/aplusb/
            - '*/*/in/*'
            - '*/*/out/*'            
  genhtml:
    docker:
      - image: yosupo/library-checker-problems-deploy
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ./deploy.py --htmldir /tmp/html --htmlonly
      - store_artifacts:
          path: /tmp/html

workflows:
  version: 2
  build:
    jobs:
      - clang-compile
      - generate
      - genhtml:
          requires:
            - generate