version: 2.1

jobs:
  clang-compile:
    docker:
      - image: gcr.io/$PROJECT_ID/library-checker-problem-env
        auth:
          username: _json_key
          password: $GCR_KEY
    steps:
      - checkout
      - run:
          command: ./generate.py problems.toml --compileonly
          environment:
            CXX: clang++
            CXXFLAGS: -std=c++14 -stdlib=libc++ -Wall -Wextra
  generate:
    docker:
      - image: gcr.io/$PROJECT_ID/library-checker-problem-env
        auth:
          username: _json_key
          password: $GCR_KEY
    steps:
      - checkout
      - run: ./generate.py problems.toml
