timelimit = 10.0

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "mod_998244353.cpp"
    number = 2

[[solutions]]
    name = "correct.cpp"
