title = 'Lyndon Factorization'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/948"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "min.in"
    number = 4
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "all_same.cpp"
    number = 2
[[tests]]
    name = "fib_str.cpp"
    number = 2
[[tests]]
    name = "binary_carry.cpp"
    number = 2
[[tests]]
    name = "all_same_plus_one.cpp"
    number = 2
    
[[solutions]]
    name = "solve_and_verify.cpp"

[params]
    N_MIN = 1
    N_MAX = 500_000
