title = 'Composition of Formal Power Series'
timelimit = 10.0

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "small.cpp"
    number = 10
[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MAX = 8_000
    N_SMALL_MAX = 10
    MOD =998_244_353
