title = 'Many A + B (128 bit)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/907"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 2
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "digit_random.cpp"
    number = 2
[[tests]]
    name = "all_max_abs.cpp"
    number = 1
[[tests]]
    name = "all_zero.cpp"
    number = 1
[[tests]]
    name = "carry_up.cpp"
    number = 1

[params]
    T_MAX = 500_000
    LOG_10_A_AND_B_MAX = 37
