timelimit = 2.0

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 10

[[tests]]
    name = "uni.cpp"
    number = 2

[[tests]]
    name = "line.cpp"
    number = 2

[params]
    N_MIN = 2
    N_MAX = 500_000
    C_MIN = 1
    C_MAX = 1_000_000_000
