solution = "correct.cpp"
timelimit = 5.0

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "perm_max_random.cpp"
    number = 5
[[tests]]
    name = "perm_plus_random.cpp"
    number = 5
