solution = "correct.cpp"
verify = 'verify.cpp'
timelimit = 5.0

[[tests]]
    Name = "example.in"
    Number = 2
[[tests]]
    Name = "random.cpp"
    Number = 5
[[tests]]
    Name = "max_random.cpp"
    Number = 5
[[tests]]
    Name = "perm_max_random.cpp"
    Number = 5
[[tests]]
    Name = "perm_plus_random.cpp"
    Number = 5
