title = 'Convolution'
timelimit = 15.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/42"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 16
[[tests]]
    name = "medium.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "fft_killer.cpp"
    number = 2
[[tests]]
    name = "medium_all_zero.cpp"
    number = 1
[[tests]]
    name = "max_ans_zero.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = true
 
#[[solutions]]
#    name = "acl.cpp"
   
#[[solutions]]
#    name = "schoenhage.cpp"

[params]
    N_AND_M_MAX = 33554432
#    N_AND_M_MAX = 8388608
#    N_AND_M_MAX = 4194314
    MOD = 998244353
