title = 'Division of Polynomials'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/658"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "n_max.cpp"
    number = 5
[[tests]]
    name = "small.cpp"
    number = 10

[params]
    N_MAX = 500000
    MOD = 998244353
