title = 'Tree Path Composite Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/861"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "n_hundreds.cpp"
    number = 2
[[tests]]
    name = "tiny.in"
    number = 2
[[tests]]
    name = "typical_tree_max.cpp"
    number = 10
    
[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MIN = 1
    N_MAX = 200_000
    A_MIN = 0
    A_MAX = 998_244_352
    B_MIN = 1
    B_MAX = 998_244_352
    C_MIN = 0
    C_MAX = 998_244_352
    MOD = 998_244_353
