solution = "correct.cpp"
verify = 'verify.cpp'
timelimit = 5.0

[[tests]]
    Name = "example.in"
    Number = 1
[[tests]]
    Name = "random.cpp"
    Number = 5

[[solutions]]
    name = 'correct.cpp'
[[solutions]]
    name = 'invalid.cpp'    
    wrong = true