title = 'Vertex Set Path Composite'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/190"
[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "small.cpp"
    number = 5

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_AND_Q_MAX = 200_000
    MOD = 998244353