title = 'Permutation Tree'
timelimit = 5.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/744'

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "ascending_order.cpp"
    number = 3
[[tests]]
    name = "descending_order.cpp"
    number = 3
[[tests]]
    name = "swap_random.cpp"
    number = 3
[[tests]]
    name = "almost_straight.cpp"
    number = 3

[params]
    P_MIN = 0
    N_MIN = 1
    N_MAX = 1_000_000
    N_SMALL_MAX = 20
    SMALL_SWAP_NUM = 20
