title = 'Exp of Formal Power Series'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/65"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "max_all_zero.cpp"
    number = 1
[[tests]]
    name = "max_ans_zero.cpp"
    number = 1
