title = 'Shift of Sampling Points'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/680"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small_random.cpp"
    number = 4
[[tests]]
    name = "medium_random.cpp"
    number = 4
[[tests]]
    name = "max_random.cpp"
    number = 4
[[tests]]
    name = "small_overlap_type0.cpp"
    number = 4
[[tests]]
    name = "small_overlap_type1.cpp"
    number = 4
[[tests]]
    name = "near_max_overlap_type0.cpp"
    number = 4
[[tests]]
    name = "near_max_overlap_type1.cpp"
    number = 4

[params]
    N_MAX = 524288
    MOD = 998244353
