timelimit = 10.0

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random_small_tree_many_query.cpp"
    number = 10

[[tests]]
    name = "random_medium.cpp"
    number = 10

[[tests]]
    name = "random_max.cpp"
    number = 2

[[tests]]
    name = "random_many_addquery.cpp"
    number = 2

[[tests]]
    name = "random_many_sumquery.cpp"
    number = 2

[[tests]]
    name = "uni.cpp"
    number = 2

[[tests]]
    name = "binary.cpp"
    number = 2

[[tests]]
    name = "line.cpp"
    number = 2

[[solutions]]
    name = "correct_fenwicktree.cpp"
    allow_tle = false
    wrong = false

[[solutions]]
    name = "tle.cpp"
    allow_tle = true
    wrong = false

[params]
    N_MIN = 1
    N_MAX = 100_000
    Q_MIN = 1
    Q_MAX = 200_000
    A_MIN = -1_000_000_000
    A_MAX = 1_000_000_000
    X_MIN = -1_000_000_000
    X_MAX = 1_000_000_000