name: Deploy

on:
  push:
    branches: 
      - master
      - test/ci

permissions:
  contents: write

jobs:
  dispatch:  
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Problems Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: yosupo06/library-checker-judge
          event-type: prod-problems-deploy
